# Generated by Django 5.0.6 on 2024-07-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairytones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
